/* $Id: mode.h 165782 2015-05-15 18:16:30Z twu $ */
#ifndef MODE_INCLUDED
#define MODE_INCLUDED

typedef enum {STANDARD, CMET_STRANDED, CMET_NONSTRANDED, ATOI_STRANDED, ATOI_NONSTRANDED, TTOC_STRANDED, TTOC_NONSTRANDED} Mode_T;

#endif

